### ISSUE TITLE
500 (Server) Error: `Maximum function nesting level of '512' reached, aborting!`

### ISSUE THREAD

**Issue by cam-vanorman** [fusioncms/fusioncms#590]
### Describe the issue
There's a unique issue I've run into while setting up Taxonomies and Fieldsets. This issue seems to be caused by a field in a fieldset referencing a taxonomy then being assigned to a taxonomy. When this happens, I receive a `500 Error` with, "Error: `Maximum function nesting level of '512' reached, aborting!`".

An example of this would be I have a taxonomy for food pantry items (`Pantry`) and a fieldset (`Flavor Affinities`) with a taxonomy relationship field. The use case for this is to show the relationship of foods and their taste pairings (taxonomy term "strawberry" with a relationship to the taxonomy term "cheese" and taxonomy term "meat" will equal the food's flavor affinity or flavor pairing).

### To reproduce
To recreate this issue, create a fieldset with a taxonomy field, then create a taxonomy and assign it to the fieldset that was just created. You will receive an initial 500 error on save (logged with `Maximum function nesting level of '512' reached, aborting!`), then when you attempt to create a new taxonomy or attempt to view the taxonomy items, the page will hang until the php script eventually hits max amount of nesting levels allowed in the `php.ini` configuration. The default value is `xdebug.max_nesting_level = 512` and I've bumped my configuration to `1024` in order to test. Logs below will show that around the call `#42`, `Taxonomy->generateRelationships()` is called in a never ending loop due to the nature of eager loading modules using `$with`, e.g. `protected $with = ['fieldsets'];`.

### Expected behavior
For models that reference themselves, `$with` may cause the model to "self-reference" itself when generating the relationship, e.g. `Model1` calling `Model2` calling `Model1` calling `Model2`, etc.

### Screenshots
![Screen Shot 2020-07-12 at 10 23 29 PM](https://user-images.githubusercontent.com/5124234/87339555-a3abc480-c4fb-11ea-9ee7-e6337969bcbe.png)
![Screen Shot 2020-07-13 at 11 29 25 AM](https://user-images.githubusercontent.com/5124234/87340030-63007b00-c4fc-11ea-9325-4468ff9321e1.png)
![Screen Shot 2020-07-13 at 11 28 04 AM](https://user-images.githubusercontent.com/5124234/87340034-63991180-c4fc-11ea-92de-5b639b4cafb1.png)

### Logs
```
#0 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(874): is_array(Array)
#1 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(30): Illuminate\\Support\\Collection->getArrayableItems(Array)
#2 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(110): Illuminate\\Support\\Collection->__construct(Array)
#3 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(97): collect(Array)
#4 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(1138): Illuminate\\Database\\Grammar->wrapSegments(Array)
#5 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(39): Illuminate\\Database\\Query\\Grammars\\Grammar->wrap('fieldsets', true)
#6 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(99): Illuminate\\Database\\Grammar->wrapTable('fieldsets')
#7 [internal function]: Illuminate\\Database\\Grammar->Illuminate\\Database\\{closure}('fieldsets', 0)
#8 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#9 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(101): Illuminate\\Support\\Collection->map(Object(Closure))
#10 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(1138): Illuminate\\Database\\Grammar->wrapSegments(Array)
#11 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(450): Illuminate\\Database\\Query\\Grammars\\Grammar->wrap('fieldsets.id')
#12 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(212): Illuminate\\Database\\Query\\Grammars\\Grammar->whereColumn(Object(Illuminate\\Database\\Query\\JoinClause), Array)
#13 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}(Array, 0)
#14 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#15 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(213): Illuminate\\Support\\Collection->map(Object(Closure))
#16 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(196): Illuminate\\Database\\Query\\Grammars\\Grammar->compileWheresToArray(Object(Illuminate\\Database\\Query\\JoinClause))
#17 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(174): Illuminate\\Database\\Query\\Grammars\\Grammar->compileWheres(Object(Illuminate\\Database\\Query\\JoinClause))
#18 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}(Object(Illuminate\\Database\\Query\\JoinClause), 0)
#19 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#20 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(175): Illuminate\\Support\\Collection->map(Object(Closure))
#21 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(91): Illuminate\\Database\\Query\\Grammars\\Grammar->compileJoins(Object(Illuminate\\Database\\Query\\Builder), Array)
#22 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(65): Illuminate\\Database\\Query\\Grammars\\Grammar->compileComponents(Object(Illuminate\\Database\\Query\\Builder))
#23 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\\Database\\Query\\Grammars\\Grammar->compileSelect(Object(Illuminate\\Database\\Query\\Builder))
#24 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2203): Illuminate\\Database\\Query\\Builder->toSql()
#25 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2191): Illuminate\\Database\\Query\\Builder->runSelect()
#26 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2686): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#27 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2192): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#28 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(539): Illuminate\\Database\\Query\\Builder->get(Array)
#29 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php(772): Illuminate\\Database\\Eloquent\\Builder->getModels()
#30 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(144): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->get()
#31 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(587): Illuminate\\Database\\Eloquent\\Relations\\Relation->getEager()
#32 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(556): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'fieldsets', Object(Closure))
#33 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(524): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#34 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#35 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(345): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#36 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->find('1')
#37 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1732): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'find', Array)
#38 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Concerns/HasDynamicRelationships.php(43): Illuminate\\Database\\Eloquent\\Model->__call('find', Array)
#39 /home/vagrant/Code/sumofabiscuit.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1744): Fusion\\Database\\Eloquent\\Model->__call('find', Array)
#40 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Fieldtypes/TaxonomyFieldtype.php(68): Illuminate\\Database\\Eloquent\\Model::__callStatic('find', Array)
#41 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Builder.php(173): Fusion\\Fieldtypes\\TaxonomyFieldtype->generateRelationship(Object(Fusion\\Models\\Field))
#42 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Collection.php(80): Fusion\\Services\\Builders\\Builder->generateRelationships()
#43 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Collection.php(34): Fusion\\Services\\Builders\\Collection->make()
#44 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Matrix.php(64): Fusion\\Services\\Builders\\Collection->__construct('recipes')
#45 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Matrix->getBuilder()
#46 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#47 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
#48 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Taxonomy.php(46): Fusion\\Services\\Builders\\Taxonomy->__construct('flavor_affiniti...')
#49 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Taxonomy->getBuilder()
#50 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#51 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
#52 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Taxonomy.php(46): Fusion\\Services\\Builders\\Taxonomy->__construct('flavor_affiniti...')
#53 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Taxonomy->getBuilder()
#54 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#55 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
#56 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Taxonomy.php(46): Fusion\\Services\\Builders\\Taxonomy->__construct('flavor_affiniti...')
#57 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Taxonomy->getBuilder()
#58 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#59 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
#60 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Taxonomy.php(46): Fusion\\Services\\Builders\\Taxonomy->__construct('flavor_affiniti...')
#61 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Taxonomy->getBuilder()
#62 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#63 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
#64 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Taxonomy.php(46): Fusion\\Services\\Builders\\Taxonomy->__construct('flavor_affiniti...')
#65 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Taxonomy->getBuilder()
#66 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#67 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
#68 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Models/Taxonomy.php(46): Fusion\\Services\\Builders\\Taxonomy->__construct('flavor_affiniti...')
#69 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(125): Fusion\\Models\\Taxonomy->getBuilder()
#70 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(83): Fusion\\Services\\Builders\\Taxonomy->generateRelationships()
#71 /home/vagrant/Code/sumofabiscuit.com/vendor/fusioncms/cms/src/Services/Builders/Taxonomy.php(39): Fusion\\Services\\Builders\\Taxonomy->make()
```

### Other Notes
This could potentially be solved by telling the taxonomy relationship to not eager load the `fieldsets` that may have a self-referencing relationship like `taxonomy->fieldset->field->taxonomy` , e.g `return $this->belongsTo(Taxonomy::class)->without('fieldsets');`. This would prevent the self-referencing loop, but may affect the way fieldsets appear in a model's relationship query. `fieldsets` would need to be loaded in an additional query using `with('fieldsets')`

### Version and browser
Version: 6.0.0-beta.8
Browser and version: Chrome 83.0.4103.116

### Bug report checklist
- [X] I have filled out as much information as I can
- [X] I have detailed how the issue can be reproduced
- [X] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by cam-vanorman** [comment]
This issue was resolved in PR [#97](https://github.com/fusioncms/cms/pull/97). Thanks @skrolikowski!
